name: 'XML syntax check'
description: 'Check XML files if they are syntactically correct'

inputs:
  xmlfiles:   # id of input
    description: "The XML files to check for wellformedness"
    required: true
    default: "*.xml"

outputs:
#  random-number: 
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
  xmllint-path:
    description: "Path to xmllint"
    value: ${{ steps.whereis-xmllint-output.outputs.xmllint }}
  xmllint-output:
    description: "Output of xmllint check"
    value: ${{ steps.check-xmlfiles.outputs.result }}

runs:
  using: "composite"
  steps:

#    - id: env
#      run: |
#        ${{ github.action_path }}/printgithubenv.sh
#      shell: bash

    - id: whereis-xmllint-output
      run: |
        # xsltproc xmlstarlet
        sudo apt-get install libxml2-utils
        echo "::set-output name=xmllint::$(whereis xmllint)"
      shell: bash

    - id: check-xmlfiles
      run: |
        xmllint --noout --noent ${{ inputs.xmlfiles }}
        echo "::set-output name=result::$?"
      shell: bash

branding:
    icon: "book-open"
    color: "green"
