on: [push]

jobs:
  check-xmlfiles:
    runs-on: ubuntu-latest
    name: Check XML files
    steps:
    - uses: actions/checkout@v2

    - name: Display environment
      run: |
        ls -l

    - id: xml-good
      name: Testing good XML
      uses: ./
      with:
         xmlfiles: tests/good/*.xml

    - id: xml-bad
      name: Testing bad XML
      uses: ./
      with:
         xmlfiles: tests/bad/*.xml

    - run: |
        echo xmllint good result: ${{ steps.xml-good.outputs.xmllint-output }}
        echo xmllint bad result: ${{ steps.xml-bad.outputs.xmllint-output }}

#    - name: Using openSUSE Leap 15.2
#      uses: docker://opensuse/leap:15.2
