on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Display environment
      run: |
        ls -l
    - id: foo
      uses: ./
      with:
        who-to-greet: 'Mona the Octocat'

    - run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash

    - run: echo xmllint path ${{ steps.foo.outputs.xml-output }}

#    - name: Using openSUSE Leap 15.2
#      uses: docker://opensuse/leap:15.2
