on: [push]

jobs:
  check-xmlfiles:
    runs-on: ubuntu-latest
    name: Check XML files
    steps:
    - uses: actions/checkout@v2

    - name: Display environment
      run: |
        ls -l

    - id: xml
      uses: ./
      with:
         xmlfiles: tests/*.xml

    - run: |
        echo xmllint result: ${{ steps.xml.outputs.xmllint-output }}

#    - run: echo random-number ${{ steps.xml.outputs.random-number }}
#      shell: bash

#    - name: Using openSUSE Leap 15.2
#      uses: docker://opensuse/leap:15.2
